### ISSUE TITLE
Website link going nowhere

### ISSUE THREAD

**Issue by 04FoxSake** [Redot-Engine/redot-docs#25]
**Your Redot version:**
4.3
**Issue description:**
Broken website links

**URL to the documentation page:**
https://docs-latest.redotengine.org/about/introduction

- On this https://docs-latest.redotengine.org/about/introduction website, the links to https://redotengine.org/community/ and https://forum.redotengine.org/ are going nowhere.

- The Redot Foundation is pointing to https://godot.foundation/

**Comment by adikhoff** [comment]
The links have been rewritten or removed
