### ISSUE TITLE
Broken links to redot source on Contributing workflow page

### ISSUE THREAD

**Issue by Aap0** [Redot-Engine/redot-docs#33]
The "Redot source code" link goes to a 404 on the specified link below

Same goes for the "Good first issue" link

And "Githubs issue tracker" link

**URL to the documentation page:**
https://docs-latest.redotengine.org/contributing/workflow/first_steps

**Comment by kedras** [comment]
Same with https://docs-latest.redotengine.org/about/complying_with_licenses and  "third parties" and  "COPYRIGHT.txt" links.
There is wrong repo link in [migrate.py](https://github.com/Redot-Engine/redot-docs/blob/1a564a60dc3e039cfe5f8cdd4839c601984ac755/migrate.py#L157) scipt.

**Comment by Aap0** [comment]
The Redot proposal link is still broken: https://github.com/redot-engine/redot-engine-proposals

The rest of the links seem to be fine on this page
