### ISSUE TITLE
Determine squashing policy when syncing from upstream fork

### ISSUE THREAD

**Issue by adikhoff** [Redot-Engine/redot-docs#49]
We normally squash every PR but I think in this case we should keep the history intact.

Specifically referring to https://github.com/Redot-Engine/redot-docs/pull/44

**Comment by Spartan322** [comment]
It is necessary in fact for the merge from upstream not to be squashed in order to minimize conflicts and the chance git will complain. In every other case it should be squashed.

**Comment by adikhoff** [comment]
Thank you
