### ISSUE TITLE
Class doc sync with redot-engine

### ISSUE THREAD

**Issue by adikhoff** [Redot-Engine/redot-docs#54]
When running https://github.com/Redot-Engine/redot-docs/actions/workflows/sync_class_ref.yml, a pull request is created to sync class info with the docs project. However this PR seems way too large and messy.

* Determine why the PR is so large. Have the class docs drifted apart or is there an error in the translation?
* Either solve the bug or integrate the new docs

**Comment by adikhoff** [comment]
PR: https://github.com/Redot-Engine/redot-docs/pull/46/files

**Comment by Spartan322** [comment]
The point of a syncref is to be a direct update of the documentation from the engine, without it the documentation will become out of date immediately without someone manually doing it, which really shouldn't even be done, it streamlines maintenance of the documentation in a place that nobody is supposed to manually modify.

**Comment by adikhoff** [comment]
After review, the PR was integrated. Currently viewable on https://docs-experimental.redotengine.org/en/latest
